a = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(a)}')
print(f'É composto por valores imprimitiveis? {a.isprintable()}')
print(f'Só tem espaços? {a.isspace()}')
print(f'É um número? {a.isnumeric()}')
print(f'É alfabético? {a.isalpha()}')
print(f'É composto apenas por decimais? {a.isdecimal()}')
print(f'É composto apenas por digitos? {a.isdigit()}')
print(f'É um identificador de código? {a.isidentifier()}')
print(f'É alfanumérico? {a.isalnum()}')
print(f'Está em maiúsculas? {a.isupper()}')
print(f'Está em minúsculas? {a.islower()}')
print(f'Está catalizada? {a.istitle()}')
